import type { Config } from "tailwindcss";

/**
 * Ported directly from khelabase_design_system/DESIGN.md and the mockup
 * tailwind.config blocks so that markup copied from the HTML mockups renders
 * pixel-identical inside the Next.js app.
 */
const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{ts,tsx,js,jsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#b4c5ff",
        "on-secondary-container": "#6f5100",
        "on-surface-variant": "#3e4a3d",
        "inverse-primary": "#62df7d",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "outline-variant": "#bdcaba",
        "on-primary-container": "#f7fff2",
        background: "#f8f9ff",
        "surface-container": "#e6eeff",
        "primary-fixed-dim": "#62df7d",
        primary: "#006b2c",
        "on-tertiary": "#ffffff",
        "surface-tint": "#006e2d",
        "on-primary-fixed": "#002109",
        secondary: "#795900",
        "secondary-container": "#ffc329",
        "on-secondary-fixed": "#261a00",
        "surface-dim": "#d0dbed",
        outline: "#6e7b6c",
        "tertiary-container": "#316bf3",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        surface: "#f8f9ff",
        "on-secondary-fixed-variant": "#5c4300",
        "tertiary-fixed": "#dbe1ff",
        "inverse-surface": "#27313f",
        "surface-variant": "#d9e3f6",
        "secondary-fixed": "#ffdf9f",
        "on-tertiary-fixed-variant": "#003ea8",
        "surface-container-high": "#dee9fc",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#eaf1ff",
        tertiary: "#0051d5",
        "on-surface": "#121c2a",
        "surface-container-highest": "#d9e3f6",
        "on-tertiary-container": "#fefcff",
        "secondary-fixed-dim": "#f9bd22",
        "on-background": "#121c2a",
        "on-tertiary-fixed": "#00174b",
        "primary-fixed": "#7ffc97",
        "primary-container": "#00873a",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9ff",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#005320",
        // Design-system brand accents (DESIGN.md)
        emerald: "#16a34a",
        "emerald-dark": "#15803d",
        gold: "#fbbf24",
        premium: "#fbbf24",
        charcoal: "#1f2937",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        sm: "12px",
        "2xl": "48px",
        xs: "8px",
        base: "4px",
        xl: "32px",
        lg: "24px",
        gutter: "24px",
        "margin-mobile": "16px",
        md: "16px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        sans: ["Manrope", "system-ui", "sans-serif"],
        "label-md": ["Manrope"],
        "title-lg": ["Manrope"],
        "display-lg": ["Manrope"],
        "headline-lg-mobile": ["Manrope"],
        "label-sm": ["Manrope"],
        "headline-md": ["Manrope"],
        "body-lg": ["Manrope"],
        "headline-lg": ["Manrope"],
        "body-md": ["Manrope"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "12px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
      boxShadow: {
        "premium-card": "0px 4px 20px rgba(31, 41, 55, 0.05)",
        "premium-card-hover": "0px 10px 30px rgba(31, 41, 55, 0.1)",
      },
    },
  },
  plugins: [],
};

export default config;
